<?php

namespace AppBundle\Repository;

/**
 * FinancialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialRepository extends \Doctrine\ORM\EntityRepository
{
}
