imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: config_fos_userbundle.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                # for postgresql
                geometry:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\Geometry
                stbuffer:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STBuffer
                stcollect:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCollect
                stsnaptogrid:            CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSnapToGrid
                stoverlaps:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STOverlaps
            numeric_functions:
                # for postgresql
                starea:                  CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                stasbinary:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsBinary
                stasgeojson:             CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsGeoJson
                stastext:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
                stazimuth:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAzimuth
                stboundary:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STBoundary
                stcentroid:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCentroid
                stclosestpoint:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STClosestPoint
                stcontains:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                stcontainsproperly:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContainsProperly
                stcoveredby:             CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCoveredBy
                stcovers:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCovers
                stcrosses:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCrosses
                stdisjoint:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDisjoint
                stdistance:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                stdistancesphere:        CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistanceSphere
                stdwithin:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDWithin
                stenvelope:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STEnvelope
                stexpand:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STExpand
                stextent:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STExtent
                stgeomfromtext:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                stintersection:          CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersection
                stintersects:            CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STIntersects
                stlength:                CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                stlinecrossingdirection: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineCrossingDirection
                stlineinterpolatepoint:  CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLineInterpolatePoint
                stmakebox2d:             CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeBox2D
                stmakeline:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine
                stmakepoint:             CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakePoint
                stperimeter:             CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STPerimeter
                stpoint:                 CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STPoint
                stscale:                 CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STScale
                stsetsrid:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSetSRID
                stsimplify:              CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSimplify
                ststartpoint:            CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STStartPoint
                stsummary:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSummary
                sttouches:               CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STTouches
                sttransform:             CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STTransform


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
